server: 
    port: 8085
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: accounts_db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka