server: 
    port: 8086
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account_credit_db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka