server:
  port: 8083
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customers_db
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka