server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customerService
          uri: lb://customerService
          predicates:
            - Path=/api/v1/customers/**
        - id: prj-account-mngt-bank
          uri: lb://prj-account-mngt-bank
          predicates:
            - Path=/api/v1/accounts/**